server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: springboot-campus-canteen
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/tc?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

